### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by andronat**

### CODE REVIEW

**Comment by andronat** [comment]
Btw, is there any specific reason we use `range()` instead of `xrange()`?

**Comment by OmeGak** [comment]
In Python 3 `range()` is already [lazy](https://docs.python.org/3/library/functions.html#func-range).

**Comment by Eipifi** [comment]
The 'record_size' name is used on the client side too, and is sent in JSON with the /db_size request. I think it the variable name must be the same on both sides. Besides, now the client is unable to parse the response.

Files still using the 'record_size' variable name:
https://github.com/blindstore/blindstore/blob/master/client/main.py
https://github.com/blindstore/blindstore/blob/master/server/main.py

**Comment by OmeGak** [comment]
We need tests

**Comment by bogdan-kulynych** [comment]
I'm working for it, and we already have some.

**Comment by andronat** [comment]
A! Sorry I forgot that we run on Python 3.

**Comment by andronat** [comment]
I didn't want to mess with the client yet. So, I updated only the server's main. If you agree with the changes please merge, else comment. :) (usually the pull requestor shouldn't merge its own requests)

**Pull request closed without merging**
